import type { ExtractedPhoto } from "../types";

// 데모/화면 확인용 1x1 PNG (실제 PDF 없이도 사진 목록 UI를 미리 볼 수 있게 함).
const PLACEHOLDER_IMAGE =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";

export const SAMPLE_PHOTOS: ExtractedPhoto[] = [
  {
    id: "P001",
    sourceFile: "sample-report.pdf",
    page: 120,
    photoNo: "③-01",
    caption: "소단측구 균열 165m",
    section: "1구간",
    part: "배수시설",
    subPart: "소단측구",
    location: "165m",
    damageName: "균열",
    image: { dataUrl: PLACEHOLDER_IMAGE, width: 400, height: 300 },
    damageRelated: true,
    nearbyText: "③-01 소단측구 균열 165m",
    ocrText: null,
    ocrConfidence: null,
    visionInference: null,
    sourceRef: { page: 120, quote: "③-01 소단측구 균열 165m" },
    duplicateCandidate: false,
    duplicateOfIds: [],
    matchCandidates: [],
    linkedDamageIds: [],
    status: "review",
    extractionStatus: "ok",
  },
  {
    id: "P002",
    sourceFile: "sample-report.pdf",
    page: 121,
    photoNo: "③-09",
    caption: "도수로 균열 208m",
    section: "1구간",
    part: "배수시설",
    subPart: "도수로",
    location: "208m",
    damageName: "균열",
    image: { dataUrl: PLACEHOLDER_IMAGE, width: 400, height: 300 },
    damageRelated: true,
    nearbyText: "③-09 도수로 균열 208m",
    ocrText: null,
    ocrConfidence: null,
    visionInference: null,
    sourceRef: { page: 121, quote: "③-09 도수로 균열 208m" },
    duplicateCandidate: false,
    duplicateOfIds: [],
    matchCandidates: [],
    linkedDamageIds: [],
    status: "confirmed",
    extractionStatus: "ok",
  },
  {
    id: "P003",
    sourceFile: "sample-report.pdf",
    page: 122,
    photoNo: null,
    caption: "시설물 전경",
    section: null,
    part: null,
    subPart: null,
    location: null,
    damageName: null,
    image: { dataUrl: PLACEHOLDER_IMAGE, width: 400, height: 300 },
    damageRelated: "unknown",
    nearbyText: "시설물 전경",
    ocrText: null,
    ocrConfidence: null,
    visionInference: null,
    sourceRef: { page: 122, quote: "시설물 전경" },
    duplicateCandidate: false,
    duplicateOfIds: [],
    matchCandidates: [],
    linkedDamageIds: [],
    status: "review",
    extractionStatus: "ok",
  },
];
